services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pass-in-api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://$DB_USER}:${DB_PASS}@host.docker.internal:5432/${DB_DB}?schema=public
  db:
    image: postgres:13.5
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: