services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picpay-api
    restart: unless-stopped
    # depends_on:
    #   - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@host.docker.internal:5432/${DB_DB}?schema=public
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672

  queue:
    image: rabbitmq:3.13.7-management
    # build:
    #   context: .
    #   dockerfile: Dockerfile.queue
    container_name: queue
    ports:
      - "5672:5672"
      - "15672:15672"
#   db:
#     image: postgres:13.5
#     restart: always
#     container_name: postgres
#     ports:
#       - '5432:5432'
#     environment:
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=admin
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres: