###
@name=create_user
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john@doe.com",
  "password": "12345678",
  "cpf": "628.958.540-17"
}


###
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "fullName": "Bruno Santos",
  "email": "bruno@email.com",
  "password": "12345678",
  "cpf": "875.489.460-31"
}


###
POST http://localhost:3000/tranfer
Content-Type: application/json

{
  "payer": "0db8d7bd-d28b-4f18-85b9-6f5064e721a2",
  "payee": "840a1b89-faf3-415c-9f7d-8eae29501bc8",
  "amount": 100
}

###
POST http://localhost:3000/tranfer
Content-Type: application/json
# Merchant cannot transfer

{
  "payer": "92cb3ba1-e175-4100-a92b-022fe1d1e403",
  "payee": "4aa7d52d-f81f-46f3-9323-8149743489a2",
  "amount": 10
}

###
POST http://localhost:3000/tranfer
Content-Type: application/json

{
  "payer": "e5134117-83f8-40ab-b9f1-fd40d1d60560",
  "payee": "5ff4d1e7-1ab7-4d97-8deb-1062b08d526e",
  "amount": 0.99
}

###
@name=transfer
POST http://localhost:3000/tranfer
Content-Type: application/json

{
  "payer": "0db8d7bd-d28b-4f18-85b9-6f5064e721a2",
  "payee": "12f373c6-ea0b-4cd7-9eda-798800e1cb66",
  "amount": 1
}