#
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john@doe.com",
  "password": "12345678",
  "cpf": "628.958.540-17"
}


###
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "fullName": "Bruno Santos",
  "email": "bruno@email.com",
  "password": "12345678",
  "cpf": "558.199.350-55",
  "cnpj": "72.033.776/0001-19"
}